/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App.GUI;

import static App.GUI.MaHoaRSA.RSADecrypt;
import static App.GUI.MaHoaRSA.RSAEncrypt;
import App.readFile.readFile;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.Key;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Security;
import java.util.Arrays;
import java.util.Base64;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Phuc Toan
 */
public class RSA_GUI extends javax.swing.JPanel {

    private String tempPublicKey;
    private String tempPrivateKey;
    //private String tempPublicKeyBanMa;
    //private String tempPrivateKeyBanMa;
    // Lấy khóa công khai
    PublicKey publicKey;

    // Lấy khóa bí mật
    PrivateKey privateKey;

    private MaHoaRSA maHoaRSA = new MaHoaRSA();
    
    byte[] encryptedDataGlobal = null;

    public RSA_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBanMa = new javax.swing.JTextArea();
        btnGiaiMa = new javax.swing.JButton();
        btnNhapBanMa = new javax.swing.JButton();
        btnXuatBanMa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBanRo = new javax.swing.JTextArea();
        txtPublicKey = new javax.swing.JTextField();
        btnMaHoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnTaoKhoaNgauNhienofBanRo = new javax.swing.JButton();
        btnLuuKhoaBanRo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnChoosePublicKey = new javax.swing.JButton();
        btnChoosePrivateKey = new javax.swing.JButton();
        txtPrivateKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel4.setPreferredSize(new java.awt.Dimension(1153, 689));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 249, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(1153, 689));

        jPanel2.setBackground(new java.awt.Color(244, 249, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bản mã", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBanMa.setColumns(20);
        txtBanMa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtBanMa.setRows(5);
        jScrollPane3.setViewportView(txtBanMa);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 42, 502, 304));

        btnGiaiMa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGiaiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 106, 47));

        btnNhapBanMa.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnNhapBanMa.setText("Đọc bản mã từ File");
        btnNhapBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapBanMaActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapBanMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 47));

        btnXuatBanMa.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnXuatBanMa.setText("Xuất bản mã ra File");
        btnXuatBanMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBanMaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXuatBanMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 47));

        jPanel3.setBackground(new java.awt.Color(244, 249, 249));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bản rõ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N

        txtBanRo.setColumns(20);
        txtBanRo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtBanRo.setRows(5);
        jScrollPane2.setViewportView(txtBanRo);

        txtPublicKey.setEditable(false);
        txtPublicKey.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        btnMaHoa.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnMaHoa.setText("Mã hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Public key");

        btnTaoKhoaNgauNhienofBanRo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnTaoKhoaNgauNhienofBanRo.setText("Tạo khóa ngẫu nhiên");
        btnTaoKhoaNgauNhienofBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaNgauNhienofBanRoActionPerformed(evt);
            }
        });

        btnLuuKhoaBanRo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnLuuKhoaBanRo.setText("Lưu khóa vào File");
        btnLuuKhoaBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuKhoaBanRoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Private key");

        btnChoosePublicKey.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnChoosePublicKey.setText("Đọc khóa từ File");
        btnChoosePublicKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePublicKeyActionPerformed(evt);
            }
        });

        btnChoosePrivateKey.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnChoosePrivateKey.setText("Đọc khóa từ File");
        btnChoosePrivateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePrivateKeyActionPerformed(evt);
            }
        });

        txtPrivateKey.setEditable(false);
        txtPrivateKey.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtPrivateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrivateKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnTaoKhoaNgauNhienofBanRo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuuKhoaBanRo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrivateKey)
                                .addGap(6, 6, 6)
                                .addComponent(btnChoosePrivateKey))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtPublicKey)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChoosePublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChoosePublicKey, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChoosePrivateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoKhoaNgauNhienofBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuKhoaBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMaHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("HỆ MÃ RSA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(529, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(443, 443, 443))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 701));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1108, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        try {
            // lay cac input tren man hinh
            String plainText = txtBanRo.getText();
            String encryptedText = "";

            if (plainText.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập bản rõ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            // ma hoa voi public key
            byte[] plaintext = plainText.getBytes("UTF-8");
            byte[] encryptedData = maHoaRSA.RSAEncrypt(plaintext, publicKey);
            encryptedDataGlobal = encryptedData;

            // chuyen sang dang text va hien thi len man hinh
            encryptedText = Base64.getEncoder().encodeToString(encryptedData);
            txtBanMa.setText(encryptedText);
        } catch (Exception ex) {
            Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this, "Không thể mã hóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;

        }
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        try {
            String cipherText = txtBanMa.getText(); // Lấy văn bản mã hóa từ giao diện
            if (cipherText.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập bản mã", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            // Gọi hàm giải mã 
            byte[] encryptedData = encryptedDataGlobal;
            byte[] decryptedData = maHoaRSA.RSADecrypt(encryptedData, privateKey);
            String decryptedText = new String(decryptedData, "UTF-8");

            // Hiển thị kết quả lên giao diện
            txtBanRo.setText(decryptedText);
        } catch (Exception ex) {
            
            Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this, "Không thể giải mã với bản mã và khóa bí mật", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;

        }
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    private void btnTaoKhoaNgauNhienofBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaNgauNhienofBanRoActionPerformed

        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());

// Tạo cặp khóa RSA
        KeyPair keyPair = null;
        try {
            keyPair = maHoaRSA.generateKeyPair();

            // Lấy khóa công khai
            publicKey = keyPair.getPublic();

            // Lấy khóa bí mật
            privateKey = keyPair.getPrivate();

            String publicKeyStr = publicKey.toString();
            String privateKeyStr = privateKey.toString();

            txtPublicKey.setText(publicKeyStr);
            txtPrivateKey.setText(privateKeyStr);
        } catch (Exception ex) {
            Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnTaoKhoaNgauNhienofBanRoActionPerformed

    private void btnLuuKhoaBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuKhoaBanRoActionPerformed
        JFileChooser fileChooser = new JFileChooser("src/App/file/RSA");
        int result = fileChooser.showSaveDialog(this); // this là JPanel hoặc JFrame chứa nút

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                // Lấy đường dẫn tệp được chọn bởi người dùng
                String selectedFilePath = fileChooser.getSelectedFile().getAbsolutePath();
                
                // luu khoa cong khai
                maHoaRSA.saveKeyToFile(publicKey, selectedFilePath);
                
            } catch (IOException ex) {
                Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        fileChooser = new JFileChooser("src/App/file/RSA");
        result = fileChooser.showSaveDialog(this); // this là JPanel hoặc JFrame chứa nút

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                // Lấy đường dẫn tệp được chọn bởi người dùng
                String selectedFilePath = fileChooser.getSelectedFile().getAbsolutePath();
                
                // luu khoa bi mat
                maHoaRSA.saveKeyToFile(privateKey, selectedFilePath);
                
            } catch (IOException ex) {
                Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnLuuKhoaBanRoActionPerformed

    private void btnChoosePublicKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePublicKeyActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("src/App/file/RSA");
        int result = fileChooser.showOpenDialog(jPanel3);


        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                // doc khoa tu file va cap nhat lai khoa
                PublicKey key = maHoaRSA.readPublicKeyFromFile(selectedFile.getPath());
                publicKey = key;
                txtPublicKey.setText(key.toString());
            } catch (Exception ex) {
                Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tempPublicKey = txtPublicKey.getText();
    }//GEN-LAST:event_btnChoosePublicKeyActionPerformed

    private void btnChoosePrivateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePrivateKeyActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("src/App/file/RSA");
        int result = fileChooser.showOpenDialog(jPanel3);

        //eadFile readFileText = new readFile();

        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                                // doc khoa tu file va cap nhat lai khoa

                PrivateKey key = maHoaRSA.readPrivateKeyFromFile(selectedFile.getPath());
                privateKey = key;
                txtPrivateKey.setText(key.toString());
            } catch (Exception ex) {
                Logger.getLogger(RSA_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tempPrivateKey = txtPrivateKey.getText();
    }//GEN-LAST:event_btnChoosePrivateKeyActionPerformed

    private void txtPrivateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrivateKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrivateKeyActionPerformed

    private void btnNhapBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapBanMaActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("src/App/file/RSA");
        int result = fileChooser.showOpenDialog(jPanel3);

        readFile readFileText = new readFile();

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
                            // doc ban ma tu file 

            String banMa = readFileText.readTextFromFile(selectedFile.getPath());
            txtBanMa.setText(banMa);
        }
    }//GEN-LAST:event_btnNhapBanMaActionPerformed

    private void btnXuatBanMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBanMaActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("src/App/file/RSA");
        int result = fileChooser.showSaveDialog(this); // this là JPanel hoặc JFrame chứa nút

        if (result == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn tệp được chọn bởi người dùng
            String selectedFilePath = fileChooser.getSelectedFile().getAbsolutePath();

            // Lấy khóa từ trường text hoặc từ đâu đó trong ứng dụng
            String banMa = txtBanMa.getText();
            try (FileWriter writer = new FileWriter(selectedFilePath + ".txt")) {
                writer.write(banMa);
                writer.close();
                JOptionPane.showMessageDialog(this, "Bản mã đã được lưu vào " + selectedFilePath + ".txt", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu bản mã!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnXuatBanMaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoosePrivateKey;
    private javax.swing.JButton btnChoosePublicKey;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnLuuKhoaBanRo;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnNhapBanMa;
    private javax.swing.JButton btnTaoKhoaNgauNhienofBanRo;
    private javax.swing.JButton btnXuatBanMa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtBanMa;
    private javax.swing.JTextArea txtBanRo;
    private javax.swing.JTextField txtPrivateKey;
    private javax.swing.JTextField txtPublicKey;
    // End of variables declaration//GEN-END:variables
}
